### ISSUE TITLE
Trying to convert a .bin produces a 0kb PatchedISO

### ISSUE THREAD

**Issue by evan64** [cr4zymanz0r/PS1_De-Dither#2]
.bat directory "F:\popstarter\newbof4\"
Source File: "F:\popstarter\newbof3\Breath of Fire IV (USA).bin"
Creating patched file...
The system cannot find the path specified.
File patched. Please rename with original file extension.
Press any key to continue . .

**Comment by cr4zymanz0r** [comment]
I just tested with the same path and file name and it worked fine. Have you tried the newest release? There was originally an early version that had issues with some folder/file names.

**Comment by cr4zymanz0r** [comment]
- No response from person who originally opened the issue.
- Sounds like an issue from an older version.
- Can not replicate issue in current version.
