### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by leonquest** [cr4zymanz0r/PS1_De-Dither#4]
I wanted to ask about how this tool works in regard to the de-dithering of PS1 ISOs. Some of the action replay codes created by Chris Comvell turn off interlacing, and some have a different code for the background, foreground, sprites, etc, does this tool keep this in mind? How does this tool work, as in how does it find the code on each game? does it apply it to all of the elements, or does it only work with background dithering? Any chance this tool can also turn off interlacing where possible?

**Comment by cr4zymanz0r** [comment]
This patcher is fairly simple in what it does. It essentially just looks through the ISO for hex pattern that correlates with dithering being enabled, then changes it to be disabled. This will disable ALL instances of dithering found.

As for interlacing, this tool does not handle that at all. If I had more technical information and examples of PS1 interlacing being disabled then I might could make a very similar version of this tool, assuming it follows some kind of set hex pattern and not very unique per interlaced game.

**Comment by leonquest** [comment]
Very cool man, thanks for the reply. I wish I could give you more technical insights, but it is way above my knowledge level. If you are feeling like trying something new, Chris Comvell might lead you into the right direction, if not, it's ok, the PS1 library is already miles better with these de-dithering patches.

**Comment by cr4zymanz0r** [comment]
- No issue with de-dithering patcher; was a question about potentials for other functionality (would be a separate new tool if it existed)
